### ISSUE TITLE
How to process data?

### ISSUE THREAD

**Issue by DongZheng0030** [zhenql/finance_bond_analysis#2]
Hi, Ranzhen! I am very sorry to bother you. I am a student and want to study the next POI recommendation. But when I look at your code, I have some problems.
1.	There is no category information in the original Gowalla data set. How do you process POI category information?
2.	Web Site: 'http://lbai5.web.engr.illinois.edu/data/' has been suspended. Can you provide your experimental data?
Thank you very much!

**Comment by zhenql** [comment]
try to download from my drive: https://drive.google.com/file/d/1t71hTf3KA1TkQD_mLfs-cD2ueXLBRw7x
