### ISSUE TITLE
Length of encoder and decoder

### ISSUE THREAD

**Issue by Charlie1994** [zhenql/finance_bond_analysis#3]
Hi there,
I am quite confused about the length of encoder and decoder you set in the code. When the variable default is set to be False (the default value in your example config file), then the length of encoder = length of decoder + 1.
It doesn't make sense, as the encoder already takes the predicted POI's information. When I change encoder length == decoder length, the performance degraded.
Could you please explain it?

Thank you!

**Comment by zhenql** [comment]
@Charlie1994  

sorry I notice the issue just now. the last node of encoder is current node (means t=T), you can find the full framework in paper. TMCA model inputed 1……T feature and 1……(T-1) labels and output the label of T.
